/**
 * Token Usage Storage Service
 *
 * Tracks token usage per agent session with in-memory storage and
 * optional periodic flush to ~/.crewly/token-usage.json.
 *
 * @module services/monitoring/token-usage.service
 */

import { promises as fs } from 'fs';
import * as path from 'path';

/** File name for persisting token usage data */
const TOKEN_USAGE_FILE = 'token-usage.json';

/** Interval in milliseconds between periodic flushes to disk (5 minutes) */
const FLUSH_INTERVAL_MS = 300_000;

/**
 * A single token usage event recorded after an agent message
 */
export interface TokenUsageEvent {
  /** Timestamp of the usage event */
  timestamp: string;
  /** Agent identifier */
  agentId: string;
  /** Number of input tokens consumed */
  input: number;
  /** Number of output tokens generated */
  output: number;
  /** AI model used for this event */
  model: string;
  /** Optional task ID for per-task tracking */
  taskId?: string;
  /**
   * Portion of `input` the provider served from its prompt cache (billed at
   * a fraction of the input rate). Absent when the runtime cannot tell.
   */
  cachedInput?: number;
  /** Model round-trips the run took (agentic steps). Absent when unknown. */
  steps?: number;
  /**
   * Of `cachedInput`, the tokens written to the cache (billed above the input
   * rate) rather than read from it. Claude only; absent when unknown.
   */
  cacheWrite?: number;
}

/** Optional per-event detail beyond the raw input/output counts. */
export interface TokenUsageDetail {
  cachedInput?: number;
  /** See {@link TokenUsageEvent.cacheWrite}. */
  cacheWrite?: number;
  steps?: number;
  /**
   * When the usage actually happened, ISO-8601.
   *
   * Backfilled sources (a Claude Code transcript read minutes later) must pass
   * the turn's own timestamp, otherwise every event lands at import time and
   * any per-day or per-hour view of the data is wrong.
   */
  timestamp?: string;
}

/**
 * Per-session token usage record containing all events and aggregates
 */
export interface SessionUsageRecord {
  /** Session name */
  sessionName: string;
  /** Agent identifier associated with this session */
  agentId: string;
  /** Total input tokens across all events */
  totalInput: number;
  /** Total output tokens across all events */
  totalOutput: number;
  /** Number of usage events recorded */
  eventCount: number;
  /** Total cached (cache-hit) input tokens across all events; absent on records written before 2026-09-18 */
  totalCachedInput?: number;
  /** Individual usage events */
  events: TokenUsageEvent[];
}

/**
 * Aggregated usage summary for a single agent
 */
export interface AgentUsageSummary {
  /** Total input tokens consumed by this agent */
  totalInput: number;
  /** Total output tokens generated by this agent */
  totalOutput: number;
  /** Number of usage events */
  eventCount: number;
}

/**
 * Per-session summary for dashboard display
 */
export interface SessionUsageSummary {
  /** Session name */
  sessionName: string;
  /** Agent identifier */
  agentId: string;
  /** Total input tokens */
  totalInput: number;
  /** Total output tokens */
  totalOutput: number;
  /** Number of events */
  eventCount: number;
  /** Total cache-hit input tokens, when the runtime reports them */
  totalCachedInput?: number;
  /** Computed cost in USD based on model pricing */
  cost: number;
  /** Per-model breakdown of token usage */
  modelBreakdown: ModelUsageBreakdown[];
}

/**
 * Token usage breakdown for a specific model
 */
export interface ModelUsageBreakdown {
  /** Model identifier */
  model: string;
  /** Input tokens for this model */
  inputTokens: number;
  /** Output tokens for this model */
  outputTokens: number;
  /** Computed cost for this model in USD */
  cost: number;
}

/**
 * Per-model token cost rates in USD per token.
 * Used for server-side cost calculation.
 */
export const TOKEN_COSTS: Record<string, { input: number; output: number; cachedInput?: number }> = {
  // DeepSeek — keyed the way the in-process runtime reports its model
  // (`provider/modelId`). Peak-hour rates from api-docs.deepseek.com (the
  // off-peak rate is half); `deepseek-chat` is the flash tier's alias.
  // `cachedInput` is the cache-HIT rate: DeepSeek bills a hit at ~2% of a
  // miss, so pricing every input token at the miss rate overstated an
  // orchestrator's spend ~40× (2026-09-18).
  'deepseek/deepseek-chat': { input: 0.0000003, cachedInput: 0.000000006, output: 0.0000012 },
  'deepseek/deepseek-flash': { input: 0.0000003, cachedInput: 0.000000006, output: 0.0000012 },
  'deepseek/deepseek-v4-flash': { input: 0.0000003, cachedInput: 0.000000006, output: 0.0000012 },
  'deepseek/deepseek-v4-pro': { input: 0.00000132, cachedInput: 0.000000044, output: 0.00000396 },
  'deepseek/deepseek-reasoner': { input: 0.00000132, cachedInput: 0.000000044, output: 0.00000396 },
  'claude-3-opus': { input: 0.000015, output: 0.000075 },
  'claude-3-5-sonnet': { input: 0.000003, output: 0.000015 },
  'claude-3-haiku': { input: 0.00000025, output: 0.00000125 },
  'claude-opus-4-20250514': { input: 0.000015, output: 0.000075 },
  'claude-sonnet-4-20250514': { input: 0.000003, output: 0.000015 },
  'claude-haiku-4-20250506': { input: 0.00000025, output: 0.00000125 },
  'gemini-3-flash-preview': { input: 0.0000001, output: 0.0000004 },
  'gemini-2.5-flash-preview-05-20': { input: 0.00000015, output: 0.0000006 },
  'gemini-2.0-flash': { input: 0.0000001, output: 0.0000004 },
  'gpt-4o': { input: 0.000005, output: 0.000015 },
  'gpt-4o-mini': { input: 0.00000015, output: 0.0000006 },
  default: { input: 0.000003, output: 0.000015 },
};

/**
 * Calculate the cost for a given number of tokens and model.
 *
 * When the model has a `cachedInput` rate and the caller passes how many of
 * the input tokens were cache hits, those tokens are billed at the hit rate
 * and only the remainder at the full input rate.
 *
 * @param inputTokens - Total input tokens for the call(s), cache hits included
 * @param outputTokens - Number of output tokens
 * @param model - Model identifier
 * @param cachedInputTokens - Portion of `inputTokens` served from cache (default 0)
 * @returns Cost in USD
 */
export function calculateCost(
  inputTokens: number,
  outputTokens: number,
  model: string,
  cachedInputTokens = 0,
): number {
  const rates = TOKEN_COSTS[model] || TOKEN_COSTS.default;
  const cached = rates.cachedInput !== undefined ? Math.min(Math.max(cachedInputTokens, 0), inputTokens) : 0;
  return (inputTokens - cached) * rates.input + cached * (rates.cachedInput ?? 0) + outputTokens * rates.output;
}

/**
 * Stores a pre-calculated cost override for a session.
 * Used when the caller has more accurate cost data (e.g., cache-aware pricing
 * from Claude Code JSONL files).
 */
const sessionCostOverrides = new Map<string, number>();

/**
 * Set a cost override for a session. When present, getSummary() uses this
 * instead of recalculating from events.
 */
export function setSessionCostOverride(sessionName: string, cost: number): void {
  sessionCostOverrides.set(sessionName, cost);
}

/**
 * Get a cost override if one exists.
 */
export function getSessionCostOverride(sessionName: string): number | undefined {
  return sessionCostOverrides.get(sessionName);
}

/**
 * Service for tracking and aggregating token usage across agent sessions.
 *
 * Uses an in-memory Map keyed by sessionName, with optional periodic
 * flush to ~/.crewly/token-usage.json for persistence across restarts.
 *
 * @example
 * ```typescript
 * const service = TokenUsageService.getInstance();
 * service.recordUsage('session-1', 'agent-a', 500, 200, 'claude-3-opus');
 * const summary = service.getUsageByAgent('agent-a');
 * ```
 */
export class TokenUsageService {
  private static instance: TokenUsageService | null = null;

  /** In-memory storage keyed by session name */
  private readonly sessions: Map<string, SessionUsageRecord> = new Map();

  /** Active task context per session (sessionName → { taskId, runId }) */
  private readonly taskContexts: Map<string, { taskId: string; runId?: string } | null> = new Map();

  /** Timer handle for periodic flush */
  private flushTimer: ReturnType<typeof setInterval> | null = null;

  /** Directory for persisting usage data */
  private readonly storageDir: string;

  /**
   * Create a new TokenUsageService instance
   *
   * @param storageDir - Directory for persistence file (defaults to ~/.crewly)
   */
  constructor(storageDir?: string) {
    this.storageDir = storageDir ?? path.join(process.env.HOME || '~', '.crewly');
  }

  /**
   * Get the singleton TokenUsageService instance
   *
   * @returns The shared TokenUsageService instance
   */
  static getInstance(): TokenUsageService {
    if (!TokenUsageService.instance) {
      TokenUsageService.instance = new TokenUsageService();
    }
    return TokenUsageService.instance;
  }

  /**
   * Reset the singleton instance (for testing)
   */
  static resetInstance(): void {
    if (TokenUsageService.instance) {
      TokenUsageService.instance.stopPeriodicFlush();
    }
    TokenUsageService.instance = null;
  }

  /**
   * Record a single token usage event for a session.
   *
   * Creates the session record if it doesn't exist, then appends the event
   * and updates running totals.
   *
   * @param sessionName - The session name (e.g. 'crewly-orc')
   * @param agentId - The agent identifier
   * @param input - Number of input tokens consumed
   * @param output - Number of output tokens generated
   * @param model - AI model identifier used
   * @param taskId - Optional task the usage belongs to
   * @param detail - Optional cache-hit and step counts for this event
   */
  recordUsage(
    sessionName: string,
    agentId: string,
    input: number,
    output: number,
    model: string,
    taskId?: string,
    detail?: TokenUsageDetail,
  ): void {
    let record = this.sessions.get(sessionName);
    if (!record) {
      record = {
        sessionName,
        agentId,
        totalInput: 0,
        totalOutput: 0,
        eventCount: 0,
        events: [],
      };
      this.sessions.set(sessionName, record);
    }

    // Auto-apply task context if no explicit taskId provided
    const ctx = this.taskContexts.get(sessionName);
    const effectiveTaskId = taskId ?? ctx?.taskId ?? undefined;

    const event: TokenUsageEvent = {
      timestamp: detail?.timestamp ?? new Date().toISOString(),
      agentId,
      input,
      output,
      model,
      taskId: effectiveTaskId,
      ...(detail?.cachedInput !== undefined ? { cachedInput: detail.cachedInput } : {}),
      ...(detail?.steps !== undefined ? { steps: detail.steps } : {}),
      ...(detail?.cacheWrite ? { cacheWrite: detail.cacheWrite } : {}),
    };

    record.events.push(event);
    record.totalInput += input;
    record.totalOutput += output;
    record.eventCount += 1;
    if (detail?.cachedInput !== undefined) {
      record.totalCachedInput = (record.totalCachedInput ?? 0) + detail.cachedInput;
    }
  }

  /**
   * Set a cache-aware cost override for a session.
   * Used when the caller has pre-calculated cost with proper cache pricing.
   */
  overrideSessionCost(sessionName: string, cost: number): void {
    setSessionCostOverride(sessionName, cost);
  }

  /**
   * Get aggregated token usage for a specific agent across all sessions.
   *
   * @param agentId - The agent identifier to query
   * @returns Aggregated usage summary for the agent
   */
  getUsageByAgent(agentId: string): AgentUsageSummary {
    let totalInput = 0;
    let totalOutput = 0;
    let eventCount = 0;

    for (const record of this.sessions.values()) {
      if (record.agentId === agentId) {
        totalInput += record.totalInput;
        totalOutput += record.totalOutput;
        eventCount += record.eventCount;
      }
    }

    return { totalInput, totalOutput, eventCount };
  }

  /**
   * Get per-session usage summaries for the dashboard.
   *
   * @returns Array of session usage summaries
   */
  getUsageBySessions(taskId?: string): SessionUsageSummary[] {
    const summaries: SessionUsageSummary[] = [];

    for (const record of this.sessions.values()) {
      // Filter events by taskId if provided
      const events = taskId
        ? record.events.filter(e => e.taskId === taskId)
        : record.events;

      if (taskId && events.length === 0) continue;

      // Compute per-model breakdown
      const modelMap = new Map<string, { input: number; output: number; cached: number }>();
      let filteredInput = 0;
      let filteredOutput = 0;

      for (const event of events) {
        const existing = modelMap.get(event.model) || { input: 0, output: 0, cached: 0 };
        existing.input += event.input;
        existing.output += event.output;
        existing.cached += event.cachedInput ?? 0;
        modelMap.set(event.model, existing);
        filteredInput += event.input;
        filteredOutput += event.output;
      }

      const modelBreakdown: ModelUsageBreakdown[] = [];
      for (const [model, usage] of modelMap) {
        modelBreakdown.push({
          model,
          inputTokens: usage.input,
          outputTokens: usage.output,
          cost: calculateCost(usage.input, usage.output, model, usage.cached),
        });
      }

      const calculatedCost = modelBreakdown.reduce((sum, m) => sum + m.cost, 0);
      // Use cache-aware cost override if available (from Claude JSONL sync)
      const costOverride = !taskId ? getSessionCostOverride(record.sessionName) : undefined;
      const totalCost = costOverride ?? calculatedCost;

      summaries.push({
        sessionName: record.sessionName,
        agentId: record.agentId,
        totalInput: taskId ? filteredInput : record.totalInput,
        totalOutput: taskId ? filteredOutput : record.totalOutput,
        eventCount: taskId ? events.length : record.eventCount,
        ...(record.totalCachedInput !== undefined
          ? {
              totalCachedInput: taskId
                ? events.reduce((sum, e) => sum + (e.cachedInput ?? 0), 0)
                : record.totalCachedInput,
            }
          : {}),
        cost: totalCost,
        modelBreakdown,
      });
    }

    return summaries;
  }

  /**
   * Set the current task context for a session.
   * All subsequent recordUsage calls for this session will be tagged with the taskId.
   *
   * @param sessionName - Session name
   * @param taskId - Task ID to associate, or null to clear
   * @param runId - Optional run ID for precise run-level attribution
   */
  setTaskContext(sessionName: string, taskId: string | null, runId?: string): void {
    if (taskId === null) {
      this.taskContexts.set(sessionName, null);
    } else {
      this.taskContexts.set(sessionName, { taskId, runId });
    }
  }

  /**
   * Get the current task context for a session (taskId only, backward compatible).
   *
   * @param sessionName - Session name
   * @returns Current task ID or null
   */
  getTaskContext(sessionName: string): string | null {
    const ctx = this.taskContexts.get(sessionName);
    return ctx?.taskId ?? null;
  }

  /**
   * Get the full task+run context for a session.
   *
   * @param sessionName - Session name
   * @returns Object with taskId and optional runId, or null if no context
   */
  getRunContext(sessionName: string): { taskId: string; runId?: string } | null {
    return this.taskContexts.get(sessionName) ?? null;
  }

  /**
   * Get aggregated token usage grouped by task ID.
   *
   * @returns Map of taskId to aggregated token totals
   */
  getUsageByTask(): Map<string, { taskId: string; totalInput: number; totalOutput: number; eventCount: number; cost: number }> {
    const taskMap = new Map<string, { taskId: string; totalInput: number; totalOutput: number; eventCount: number; cost: number }>();

    for (const record of this.sessions.values()) {
      for (const event of record.events) {
        const tid = event.taskId ?? 'unassigned';
        const existing = taskMap.get(tid) ?? { taskId: tid, totalInput: 0, totalOutput: 0, eventCount: 0, cost: 0 };
        existing.totalInput += event.input;
        existing.totalOutput += event.output;
        existing.eventCount += 1;
        existing.cost += calculateCost(event.input, event.output, event.model);
        taskMap.set(tid, existing);
      }
    }

    return taskMap;
  }

  /**
   * Get token usage events for a specific session recorded after a given timestamp.
   * Used to compute the token delta for a single Request when the orchestrator
   * handles the work directly (no WorkItem delegation).
   *
   * @param sessionName - The session to query (e.g. 'crewly-orc')
   * @param since - Only return events recorded at or after this time
   * @param until - Only return events before this time (defaults to now)
   * @returns Aggregated input tokens, output tokens, and cost in the window
   */
  getSessionUsageSince(
    sessionName: string,
    since: Date,
    until?: Date,
  ): { inputTokens: number; outputTokens: number; cost: number } {
    const record = this.sessions.get(sessionName);
    if (!record) return { inputTokens: 0, outputTokens: 0, cost: 0 };

    const sinceMs = since.getTime();
    const untilMs = until ? until.getTime() : Infinity;
    let inputTokens = 0;
    let outputTokens = 0;
    let cost = 0;

    for (const event of record.events) {
      const eventMs = new Date(event.timestamp).getTime();
      if (eventMs >= sinceMs && eventMs <= untilMs) {
        inputTokens += event.input;
        outputTokens += event.output;
        // Cache-aware: a cache hit is billed at a fraction of the miss rate,
        // and the team budget gate keys on this figure — pricing every input
        // token at the miss rate would trip monthly USD caps ~40x early.
        cost += calculateCost(event.input, event.output, event.model, event.cachedInput ?? 0);
      }
    }

    return { inputTokens, outputTokens, cost };
  }

  /**
   * Clear all tracked token usage data.
   */
  resetUsage(): void {
    this.sessions.clear();
  }

  /**
   * Start periodic flush of usage data to disk.
   *
   * Writes the current in-memory state to ~/.crewly/token-usage.json
   * at a fixed interval.
   */
  startPeriodicFlush(): void {
    if (this.flushTimer) return;
    this.flushTimer = setInterval(() => {
      this.flushToDisk().catch(() => {
        // Silently ignore flush errors — data is still in memory
      });
    }, FLUSH_INTERVAL_MS);
    // Allow Node to exit even if timer is running
    if (this.flushTimer.unref) {
      this.flushTimer.unref();
    }
  }

  /**
   * Stop the periodic flush timer.
   */
  stopPeriodicFlush(): void {
    if (this.flushTimer) {
      clearInterval(this.flushTimer);
      this.flushTimer = null;
    }
  }

  /**
   * Flush current usage data to disk.
   *
   * Writes sessions as a JSON array to the storage directory.
   */
  async flushToDisk(): Promise<void> {
    const filePath = path.join(this.storageDir, TOKEN_USAGE_FILE);
    const data = Array.from(this.sessions.values());
    await fs.mkdir(this.storageDir, { recursive: true });
    await fs.writeFile(filePath, JSON.stringify(data, null, 2), 'utf-8');
  }

  /**
   * Load previously persisted usage data from disk.
   *
   * Merges loaded data into the current in-memory state.
   */
  async loadFromDisk(): Promise<void> {
    const filePath = path.join(this.storageDir, TOKEN_USAGE_FILE);
    try {
      const raw = await fs.readFile(filePath, 'utf-8');
      const records: SessionUsageRecord[] = JSON.parse(raw);
      dropCrossSessionDuplicates(records);
      for (const record of records) {
        if (!this.sessions.has(record.sessionName)) {
          this.sessions.set(record.sessionName, record);
        }
      }
    } catch {
      // File doesn't exist or is invalid — start fresh
    }
  }

  /**
   * Get the number of tracked sessions (for testing).
   *
   * @returns Number of sessions in the store
   */
  getSessionCount(): number {
    return this.sessions.size;
  }
}

/**
 * Remove usage events that appear in more than one session's record.
 *
 * Two agents cannot produce the same usage at the same millisecond. Before the
 * shared-cwd guard (2026-09-22) the transcript sync pointed several agents at
 * one foreign transcript, so each of them was booked every one of its turns —
 * about 130 turns copied into five records. Every copy is dropped: the turns
 * belonged to none of them. Totals are recomputed for records that changed.
 *
 * @param records - Records as loaded from disk; modified in place
 * @returns How many events were removed
 */
export function dropCrossSessionDuplicates(records: SessionUsageRecord[]): number {
  const key = (e: TokenUsageEvent) => `${e.timestamp}|${e.input}|${e.cachedInput ?? ''}|${e.output}|${e.model}`;
  const owners = new Map<string, Set<string>>();
  for (const r of records) {
    for (const e of r.events ?? []) {
      const k = key(e);
      const set = owners.get(k) ?? new Set<string>();
      set.add(r.sessionName);
      owners.set(k, set);
    }
  }
  let removed = 0;
  for (const r of records) {
    const before = (r.events ?? []).length;
    const seen = new Set<string>();
    r.events = (r.events ?? []).filter((e) => {
      const k = key(e);
      // Shared with another session: not this one's. Repeated within this
      // session (the same turn booked on several passes): keep one.
      if ((owners.get(k)?.size ?? 0) > 1 || seen.has(k)) return false;
      seen.add(k);
      return true;
    });
    if (r.events.length === before) continue;
    removed += before - r.events.length;
    r.eventCount = r.events.length;
    r.totalInput = r.events.reduce((n, e) => n + e.input, 0);
    r.totalOutput = r.events.reduce((n, e) => n + e.output, 0);
    const cached = r.events.reduce((n, e) => n + (e.cachedInput ?? 0), 0);
    if (r.totalCachedInput !== undefined || cached > 0) r.totalCachedInput = cached;
  }
  return removed;
}
