/**
 * Token Usage Storage Service
 *
 * Tracks token usage per agent session with in-memory storage and
 * optional periodic flush to ~/.crewly/token-usage.json.
 *
 * @module services/monitoring/token-usage.service
 */

import { promises as fs } from 'fs';
import * as path from 'path';
import { calculateCost as calculateCacheAwareCost, resolveRate } from './model-pricing.js';
import { traceUsage } from '../trace/trace-recorder.js';
import { atomicWriteFile, readJsonStore, CorruptJsonFileError, type JsonStoreRead } from '../../utils/file-io.utils.js';
import { LoggerService, type ComponentLogger } from '../core/logger.service.js';

/** File name for persisting token usage data */
const TOKEN_USAGE_FILE = 'token-usage.json';

/** Interval in milliseconds between periodic flushes to disk (5 minutes) */
const FLUSH_INTERVAL_MS = 300_000;

/**
 * A single token usage event recorded after an agent message
 */
export interface TokenUsageEvent {
  /** Timestamp of the usage event */
  timestamp: string;
  /** Agent identifier */
  agentId: string;
  /** Number of input tokens consumed */
  input: number;
  /** Number of output tokens generated */
  output: number;
  /** AI model used for this event */
  model: string;
  /** Optional task ID for per-task tracking */
  taskId?: string;
  /**
   * Portion of `input` the provider served from its prompt cache (billed at
   * a fraction of the input rate). Absent when the runtime cannot tell.
   */
  cachedInput?: number;
  /** Model round-trips the run took (agentic steps). Absent when unknown. */
  steps?: number;
  /**
   * Of `cachedInput`, the tokens written to the cache (billed above the input
   * rate) rather than read from it. Claude only; absent when unknown.
   */
  cacheWrite?: number;
  /**
   * Runtime that produced the event (`codex-cli`, `antigravity-cli`, …), set
   * by the sources that know it. Absent on older events and on sources that
   * only know the model; {@link runtimeOfEvent} then infers it from the model.
   */
  runtime?: string;
  /**
   * Run trace the session was working on when the usage happened
   * (specs/2026-10-03-run-traces.md). Absent outside a trace.
   */
  traceId?: string;
  /**
   * Provider message id of the turn (Claude transcripts: `message.id`), so a
   * later import can dedupe by id. Absent on older events and on sources
   * without one (specs/2026-10-03-usage-ledger-durability.md).
   */
  messageId?: string;
}

/** Optional per-event detail beyond the raw input/output counts. */
export interface TokenUsageDetail {
  cachedInput?: number;
  /** See {@link TokenUsageEvent.cacheWrite}. */
  cacheWrite?: number;
  steps?: number;
  /**
   * When the usage actually happened, ISO-8601.
   *
   * Backfilled sources (a Claude Code transcript read minutes later) must pass
   * the turn's own timestamp, otherwise every event lands at import time and
   * any per-day or per-hour view of the data is wrong.
   */
  timestamp?: string;
  /** See {@link TokenUsageEvent.runtime}. */
  runtime?: string;
  /** See {@link TokenUsageEvent.traceId}; looked up from the session when absent. */
  traceId?: string;
  /** See {@link TokenUsageEvent.messageId}. */
  messageId?: string;
}

/**
 * Per-session token usage record containing all events and aggregates
 */
export interface SessionUsageRecord {
  /** Session name */
  sessionName: string;
  /** Agent identifier associated with this session */
  agentId: string;
  /** Total input tokens across all events */
  totalInput: number;
  /** Total output tokens across all events */
  totalOutput: number;
  /** Number of usage events recorded */
  eventCount: number;
  /** Total cached (cache-hit) input tokens across all events; absent on records written before 2026-09-18 */
  totalCachedInput?: number;
  /** Individual usage events */
  events: TokenUsageEvent[];
}

/**
 * Aggregated usage summary for a single agent
 */
export interface AgentUsageSummary {
  /** Total input tokens consumed by this agent */
  totalInput: number;
  /** Total output tokens generated by this agent */
  totalOutput: number;
  /** Number of usage events */
  eventCount: number;
}

/**
 * Per-session summary for dashboard display
 */
export interface SessionUsageSummary {
  /** Session name */
  sessionName: string;
  /** Agent identifier */
  agentId: string;
  /** Total input tokens */
  totalInput: number;
  /** Total output tokens */
  totalOutput: number;
  /** Number of events */
  eventCount: number;
  /** Total cache-hit input tokens, when the runtime reports them */
  totalCachedInput?: number;
  /** Computed cost in USD based on model pricing */
  cost: number;
  /** Per-model breakdown of token usage */
  modelBreakdown: ModelUsageBreakdown[];
}

/**
 * Token usage breakdown for a specific model
 */
export interface ModelUsageBreakdown {
  /** Model identifier */
  model: string;
  /** Input tokens for this model */
  inputTokens: number;
  /** Output tokens for this model */
  outputTokens: number;
  /** Computed cost for this model in USD */
  cost: number;
}

/**
 * Per-model token cost rates in USD per token.
 * Used for server-side cost calculation.
 */
export const TOKEN_COSTS: Record<string, { input: number; output: number; cachedInput?: number }> = {
  // DeepSeek — keyed the way the in-process runtime reports its model
  // (`provider/modelId`). Peak-hour rates from api-docs.deepseek.com (the
  // off-peak rate is half); `deepseek-chat` is the flash tier's alias.
  // `cachedInput` is the cache-HIT rate: DeepSeek bills a hit at ~2% of a
  // miss, so pricing every input token at the miss rate overstated an
  // orchestrator's spend ~40× (2026-09-18).
  'deepseek/deepseek-chat': { input: 0.0000003, cachedInput: 0.000000006, output: 0.0000012 },
  'deepseek/deepseek-flash': { input: 0.0000003, cachedInput: 0.000000006, output: 0.0000012 },
  'deepseek/deepseek-v4-flash': { input: 0.0000003, cachedInput: 0.000000006, output: 0.0000012 },
  'deepseek/deepseek-v4-pro': { input: 0.00000132, cachedInput: 0.000000044, output: 0.00000396 },
  'deepseek/deepseek-reasoner': { input: 0.00000132, cachedInput: 0.000000044, output: 0.00000396 },
  'claude-3-opus': { input: 0.000015, output: 0.000075 },
  'claude-3-5-sonnet': { input: 0.000003, output: 0.000015 },
  'claude-3-haiku': { input: 0.00000025, output: 0.00000125 },
  'claude-opus-4-20250514': { input: 0.000015, output: 0.000075 },
  'claude-sonnet-4-20250514': { input: 0.000003, output: 0.000015 },
  'claude-haiku-4-20250506': { input: 0.00000025, output: 0.00000125 },
  'gemini-3-flash-preview': { input: 0.0000001, output: 0.0000004 },
  'gemini-2.5-flash-preview-05-20': { input: 0.00000015, output: 0.0000006 },
  'gemini-2.0-flash': { input: 0.0000001, output: 0.0000004 },
  'gpt-4o': { input: 0.000005, output: 0.000015 },
  'gpt-4o-mini': { input: 0.00000015, output: 0.0000006 },
  default: { input: 0.000003, output: 0.000015 },
};

/**
 * Calculate the cost for a given number of tokens and model.
 *
 * When the model has a `cachedInput` rate and the caller passes how many of
 * the input tokens were cache hits, those tokens are billed at the hit rate
 * and only the remainder at the full input rate.
 *
 * @param inputTokens - Total input tokens for the call(s), cache hits included
 * @param outputTokens - Number of output tokens
 * @param model - Model identifier
 * @param cachedInputTokens - Portion of `inputTokens` served from cache (default 0)
 * @returns Cost in USD
 */
export function calculateCost(
  inputTokens: number,
  outputTokens: number,
  model: string,
  cachedInputTokens = 0,
): number {
  const rates = TOKEN_COSTS[model] || TOKEN_COSTS.default;
  const cached = rates.cachedInput !== undefined ? Math.min(Math.max(cachedInputTokens, 0), inputTokens) : 0;
  return (inputTokens - cached) * rates.input + cached * (rates.cachedInput ?? 0) + outputTokens * rates.output;
}

/**
 * USD cost of one recorded usage event — the one cost computation every
 * spend view uses (session windows, the team budget gate, the ticket
 * autopilot budget, the per-agent spend cap).
 *
 * The ledger holds two shapes of event:
 * - in-process runs (`provider/model`, e.g. DeepSeek): `cachedInput` is the
 *   cache-hit PART of `input`, priced with {@link TOKEN_COSTS};
 * - Claude Code transcript turns: `input` is the fresh tokens only and
 *   `cachedInput` (cache reads + `cacheWrite`) comes on top, priced with the
 *   cache-aware model-pricing table. Pricing these with {@link TOKEN_COSTS}
 *   dropped every cached token and used sonnet rates for opus.
 *
 * @param event - The usage event
 * @returns Cost in USD
 */
export function eventCostUsd(event: Pick<TokenUsageEvent, 'input' | 'output' | 'model' | 'cachedInput' | 'cacheWrite'>): number {
  const model = event.model || '';
  const legacyKey = legacyRateKey(model);
  const source = model.includes('/') ? 'default' : resolveRate(model).source;
  // An exact id wins over a family match: the cache-aware table's exact ids
  // first, then TOKEN_COSTS' exact ids (e.g. `gemini-2.5-flash-preview-05-20`),
  // and only then a family match.
  if (source === 'exact' || (source === 'family' && !legacyKey)) {
    const write = Math.max(0, event.cacheWrite ?? 0);
    const read = Math.max(0, (event.cachedInput ?? 0) - write);
    return calculateCacheAwareCost({ input: event.input, output: event.output, cacheRead: read, cacheWrite: write }, model).cost;
  }
  return calculateCost(event.input, event.output, legacyKey ?? model, event.cachedInput ?? 0);
}

/**
 * The TOKEN_COSTS key listing a model by its exact id (with or without its
 * `provider/` prefix), if any.
 *
 * @param model - Model id as recorded
 * @returns Key, or null
 */
function legacyRateKey(model: string): string | null {
  const unprefixed = model.includes('/') ? model.slice(model.indexOf('/') + 1) : model;
  return TOKEN_COSTS[model] ? model : TOKEN_COSTS[unprefixed] ? unprefixed : null;
}

/**
 * How confidently {@link eventCostUsd} priced an event's model — the same
 * branching it uses: `exact` (listed by id), `family` (matched on a family
 * substring) or `default` (nothing matched; a default rate was assumed).
 *
 * @param model - Model id as recorded
 * @returns Rate source
 */
export function eventCostRateSource(model: string): 'exact' | 'family' | 'default' {
  const m = model || '';
  const source = m.includes('/') ? 'default' : resolveRate(m).source;
  if (source === 'exact' || legacyRateKey(m)) return 'exact';
  return source;
}

/** The token figures of one event in the owner-facing unit (see {@link eventTokens}). */
export interface EventTokens {
  /** Every input token, cached ones included */
  input: number;
  /** The cached part of {@link input} (cache reads + cache writes) */
  cachedInput: number;
  output: number;
  /**
   * {@link input} + {@link output}: the RAW total, for reporting. Cache reads
   * count in full here, so it overstates what a long-lived agent costs ~10x.
   */
  total: number;
  /** Of {@link cachedInput}, the part written to the cache (Claude only) */
  cacheWrite: number;
  /**
   * The COST-WEIGHTED total ("budget tokens"): what every budget, cap and
   * boost compares. fresh input x w.input + output x w.output + cache writes
   * x w.cacheWrite + cache reads x w.cacheRead, with the weights of the
   * event's model family ({@link budgetWeightsFor}). Not rounded.
   */
  budget: number;
}

/** How many budget tokens one token of each kind is worth. */
export interface BudgetWeights {
  /** Fresh (uncached) input */
  input: number;
  /** Output */
  output: number;
  /** Tokens written to the prompt cache */
  cacheWrite: number;
  /** Tokens read from the prompt cache */
  cacheRead: number;
}

/**
 * The default budget weights, and the Claude ones: input x1 + output x1 +
 * cache writes x1.25 + cache reads x0.1. They equal the cache/input price
 * ratios of the Anthropic tiers in `model-pricing.ts` (Sonnet 0.3/3 and
 * 3.75/3, Opus 1.5/15 and 18.75/15, Haiku 0.1/1 and 1.25/1). Output stays at
 * x1 on purpose: the budget is a measure of context re-reading, not a USD
 * figure, and an owner's existing numbers keep their meaning.
 */
export const DEFAULT_BUDGET_WEIGHTS: Readonly<BudgetWeights> = Object.freeze({ input: 1, output: 1, cacheWrite: 1.25, cacheRead: 0.1 });

/** Rounds a price ratio to 3 decimals (0.3/3 is 0.09999999999999999 in floating point). */
function ratio(a: number, b: number): number {
  return b > 0 ? Math.round((a / b) * 1000) / 1000 : 0;
}

/**
 * The budget weights of a model family. Cache weights are the ratios of the
 * family's own cache price to its input price, read from the pricing table
 * (`model-pricing.ts`) so there is one source for them:
 *
 * | Family | cache read | cache write |
 * |---|---|---|
 * | Claude (opus / sonnet / haiku / fable) | 0.1 | 1.25 |
 * | OpenAI gpt-5 / codex (Codex CLI) | 0.1 | 1 (no separate write price) |
 * | DeepSeek (crewly-agent) | ~0.26 | 1 |
 * | Gemini 2.5 pro / flash (Antigravity) | ~0.25 | 1 |
 * | Unknown | {@link DEFAULT_BUDGET_WEIGHTS} |
 *
 * @param model - Model id as recorded
 * @returns Weights; `input` and `output` are always 1
 *
 * @example
 * budgetWeightsFor('claude-sonnet-5-5') // { input: 1, output: 1, cacheWrite: 1.25, cacheRead: 0.1 }
 */
export function budgetWeightsFor(model: string): BudgetWeights {
  const rate = resolveRate(model || '');
  if (rate.source === 'default') return { ...DEFAULT_BUDGET_WEIGHTS };
  return { input: 1, output: 1, cacheWrite: ratio(rate.cacheWrite, rate.input), cacheRead: ratio(rate.cacheRead, rate.input) };
}

/**
 * Whether an event's `cachedInput` is part of its `input` (true) or comes
 * on top of it (false).
 *
 * - In-process runs (`provider/model`, e.g. DeepSeek) report the provider's
 *   prompt-token count, which includes cache hits: part of `input`.
 * - Claude Code transcript turns, Codex rollouts and Antigravity record
 *   `input` as the fresh tokens only, with the cached ones on top.
 *
 * @param event - Usage event
 * @returns True when cached tokens are already inside `input`
 */
export function cachedIsPartOfInput(event: Pick<TokenUsageEvent, 'model' | 'runtime'>): boolean {
  if (event.runtime) return event.runtime === 'crewly-agent';
  return (event.model || '').includes('/');
}

/**
 * The token unit. Two figures from one function:
 *
 *   total  = input tokens (fresh + cached) + output tokens   (raw, for reports)
 *   budget = cost-weighted total (cache reads x0.1, writes x1.25 for Claude)
 *
 * Every cap, boost and budget GATE compares `budget`; `total` stays for
 * reporting and is shown beside it. Whether an account is billed by
 * subscription or by API makes no difference.
 * specs/2026-10-02-spend-cap.md §Token unit.
 *
 * @param event - Usage event
 * @returns Input (cached included), cached input, output, total
 *
 * @example
 * eventTokens({ model: 'claude-opus-5-5', input: 10, cachedInput: 990, output: 50 }).total // 1050
 * eventTokens({ model: 'deepseek/deepseek-chat', input: 1000, cachedInput: 990, output: 50 }).total // 1050
 */
export function eventTokens(
  event: Pick<TokenUsageEvent, 'model' | 'runtime' | 'input' | 'output' | 'cachedInput'> & { cacheWrite?: number },
): EventTokens {
  const raw = Math.max(0, event.input || 0);
  const cached = Math.max(0, event.cachedInput || 0);
  const output = Math.max(0, event.output || 0);
  const input = cachedIsPartOfInput(event) ? Math.max(raw, cached) : raw + cached;
  const cachedInput = Math.min(cached, input);
  const cacheWrite = Math.min(Math.max(0, event.cacheWrite || 0), cachedInput);
  const w = budgetWeightsFor(event.model);
  const budget = (input - cachedInput) * w.input + output * w.output + cacheWrite * w.cacheWrite + (cachedInput - cacheWrite) * w.cacheRead;
  return { input, cachedInput, output, total: input + output, cacheWrite, budget };
}

/**
 * Stores a pre-calculated cost override for a session.
 * Used when the caller has more accurate cost data (e.g., cache-aware pricing
 * from Claude Code JSONL files).
 */
const sessionCostOverrides = new Map<string, number>();

/**
 * Set a cost override for a session. When present, getSummary() uses this
 * instead of recalculating from events.
 */
export function setSessionCostOverride(sessionName: string, cost: number): void {
  sessionCostOverrides.set(sessionName, cost);
}

/**
 * Get a cost override if one exists.
 */
export function getSessionCostOverride(sessionName: string): number | undefined {
  return sessionCostOverrides.get(sessionName);
}

/**
 * Service for tracking and aggregating token usage across agent sessions.
 *
 * Uses an in-memory Map keyed by sessionName, with optional periodic
 * flush to ~/.crewly/token-usage.json for persistence across restarts.
 *
 * @example
 * ```typescript
 * const service = TokenUsageService.getInstance();
 * service.recordUsage('session-1', 'agent-a', 500, 200, 'claude-3-opus');
 * const summary = service.getUsageByAgent('agent-a');
 * ```
 */
export class TokenUsageService {
  private static instance: TokenUsageService | null = null;

  /** In-memory storage keyed by session name */
  private readonly sessions: Map<string, SessionUsageRecord> = new Map();

  /** Active task context per session (sessionName → { taskId, runId }) */
  private readonly taskContexts: Map<string, { taskId: string; runId?: string } | null> = new Map();

  /** Timer handle for periodic flush */
  private flushTimer: ReturnType<typeof setInterval> | null = null;

  /** Directory for persisting usage data */
  private readonly storageDir: string;

  /**
   * `not-loaded` until {@link loadFromDisk} ran; `blocked` while the file on
   * disk is bad and could not be copied aside (flushes refuse to write).
   */
  private loadState: 'not-loaded' | 'loaded' | 'blocked' = 'not-loaded';

  /** Why the ledger is blocked */
  private blockedReason: string | null = null;

  private logger: ComponentLogger | null = null;

  /**
   * Create a new TokenUsageService instance
   *
   * @param storageDir - Directory for persistence file (defaults to ~/.crewly)
   */
  constructor(storageDir?: string) {
    this.storageDir = storageDir ?? path.join(process.env.HOME || '~', '.crewly');
  }

  /**
   * Get the singleton TokenUsageService instance
   *
   * @returns The shared TokenUsageService instance
   */
  static getInstance(): TokenUsageService {
    if (!TokenUsageService.instance) {
      TokenUsageService.instance = new TokenUsageService();
    }
    return TokenUsageService.instance;
  }

  /**
   * Reset the singleton instance (for testing)
   */
  static resetInstance(): void {
    if (TokenUsageService.instance) {
      TokenUsageService.instance.stopPeriodicFlush();
    }
    TokenUsageService.instance = null;
  }

  /**
   * Record a single token usage event for a session.
   *
   * Creates the session record if it doesn't exist, then appends the event
   * and updates running totals.
   *
   * @param sessionName - The session name (e.g. 'crewly-orc')
   * @param agentId - The agent identifier
   * @param input - Number of input tokens consumed
   * @param output - Number of output tokens generated
   * @param model - AI model identifier used
   * @param taskId - Optional task the usage belongs to
   * @param detail - Optional cache-hit and step counts for this event
   */
  recordUsage(
    sessionName: string,
    agentId: string,
    input: number,
    output: number,
    model: string,
    taskId?: string,
    detail?: TokenUsageDetail,
  ): void {
    let record = this.sessions.get(sessionName);
    if (!record) {
      record = {
        sessionName,
        agentId,
        totalInput: 0,
        totalOutput: 0,
        eventCount: 0,
        events: [],
      };
      this.sessions.set(sessionName, record);
    }

    // Auto-apply task context if no explicit taskId provided
    const ctx = this.taskContexts.get(sessionName);
    const effectiveTaskId = taskId ?? ctx?.taskId ?? undefined;

    const event: TokenUsageEvent = {
      timestamp: detail?.timestamp ?? new Date().toISOString(),
      agentId,
      input,
      output,
      model,
      taskId: effectiveTaskId,
      ...(detail?.cachedInput !== undefined ? { cachedInput: detail.cachedInput } : {}),
      ...(detail?.steps !== undefined ? { steps: detail.steps } : {}),
      ...(detail?.cacheWrite ? { cacheWrite: detail.cacheWrite } : {}),
      ...(detail?.runtime ? { runtime: detail.runtime } : {}),
      ...(detail?.messageId ? { messageId: detail.messageId } : {}),
    };
    const traceId = detail?.traceId ?? traceUsage(sessionName, event);
    if (traceId) event.traceId = traceId;

    record.events.push(event);
    record.totalInput += input;
    record.totalOutput += output;
    record.eventCount += 1;
    if (detail?.cachedInput !== undefined) {
      record.totalCachedInput = (record.totalCachedInput ?? 0) + detail.cachedInput;
    }
  }

  /**
   * Set a cache-aware cost override for a session.
   * Used when the caller has pre-calculated cost with proper cache pricing.
   */
  overrideSessionCost(sessionName: string, cost: number): void {
    setSessionCostOverride(sessionName, cost);
  }

  /**
   * Get aggregated token usage for a specific agent across all sessions.
   *
   * @param agentId - The agent identifier to query
   * @returns Aggregated usage summary for the agent
   */
  getUsageByAgent(agentId: string): AgentUsageSummary {
    let totalInput = 0;
    let totalOutput = 0;
    let eventCount = 0;

    for (const record of this.sessions.values()) {
      if (record.agentId === agentId) {
        totalInput += record.totalInput;
        totalOutput += record.totalOutput;
        eventCount += record.eventCount;
      }
    }

    return { totalInput, totalOutput, eventCount };
  }

  /**
   * Get per-session usage summaries for the dashboard.
   *
   * @returns Array of session usage summaries
   */
  getUsageBySessions(taskId?: string): SessionUsageSummary[] {
    const summaries: SessionUsageSummary[] = [];

    for (const record of this.sessions.values()) {
      // Filter events by taskId if provided
      const events = taskId
        ? record.events.filter(e => e.taskId === taskId)
        : record.events;

      if (taskId && events.length === 0) continue;

      // Compute per-model breakdown
      const modelMap = new Map<string, { input: number; output: number; cached: number }>();
      let filteredInput = 0;
      let filteredOutput = 0;

      for (const event of events) {
        const existing = modelMap.get(event.model) || { input: 0, output: 0, cached: 0 };
        existing.input += event.input;
        existing.output += event.output;
        existing.cached += event.cachedInput ?? 0;
        modelMap.set(event.model, existing);
        filteredInput += event.input;
        filteredOutput += event.output;
      }

      const modelBreakdown: ModelUsageBreakdown[] = [];
      for (const [model, usage] of modelMap) {
        modelBreakdown.push({
          model,
          inputTokens: usage.input,
          outputTokens: usage.output,
          cost: calculateCost(usage.input, usage.output, model, usage.cached),
        });
      }

      const calculatedCost = modelBreakdown.reduce((sum, m) => sum + m.cost, 0);
      // Use cache-aware cost override if available (from Claude JSONL sync)
      const costOverride = !taskId ? getSessionCostOverride(record.sessionName) : undefined;
      const totalCost = costOverride ?? calculatedCost;

      summaries.push({
        sessionName: record.sessionName,
        agentId: record.agentId,
        totalInput: taskId ? filteredInput : record.totalInput,
        totalOutput: taskId ? filteredOutput : record.totalOutput,
        eventCount: taskId ? events.length : record.eventCount,
        ...(record.totalCachedInput !== undefined
          ? {
              totalCachedInput: taskId
                ? events.reduce((sum, e) => sum + (e.cachedInput ?? 0), 0)
                : record.totalCachedInput,
            }
          : {}),
        cost: totalCost,
        modelBreakdown,
      });
    }

    return summaries;
  }

  /**
   * Set the current task context for a session.
   * All subsequent recordUsage calls for this session will be tagged with the taskId.
   *
   * @param sessionName - Session name
   * @param taskId - Task ID to associate, or null to clear
   * @param runId - Optional run ID for precise run-level attribution
   */
  setTaskContext(sessionName: string, taskId: string | null, runId?: string): void {
    if (taskId === null) {
      this.taskContexts.set(sessionName, null);
    } else {
      this.taskContexts.set(sessionName, { taskId, runId });
    }
  }

  /**
   * Get the current task context for a session (taskId only, backward compatible).
   *
   * @param sessionName - Session name
   * @returns Current task ID or null
   */
  getTaskContext(sessionName: string): string | null {
    const ctx = this.taskContexts.get(sessionName);
    return ctx?.taskId ?? null;
  }

  /**
   * Get the full task+run context for a session.
   *
   * @param sessionName - Session name
   * @returns Object with taskId and optional runId, or null if no context
   */
  getRunContext(sessionName: string): { taskId: string; runId?: string } | null {
    return this.taskContexts.get(sessionName) ?? null;
  }

  /**
   * Get aggregated token usage grouped by task ID.
   *
   * @returns Map of taskId to aggregated token totals
   */
  getUsageByTask(): Map<string, { taskId: string; totalInput: number; totalOutput: number; eventCount: number; cost: number }> {
    const taskMap = new Map<string, { taskId: string; totalInput: number; totalOutput: number; eventCount: number; cost: number }>();

    for (const record of this.sessions.values()) {
      for (const event of record.events) {
        const tid = event.taskId ?? 'unassigned';
        const existing = taskMap.get(tid) ?? { taskId: tid, totalInput: 0, totalOutput: 0, eventCount: 0, cost: 0 };
        existing.totalInput += event.input;
        existing.totalOutput += event.output;
        existing.eventCount += 1;
        existing.cost += calculateCost(event.input, event.output, event.model);
        taskMap.set(tid, existing);
      }
    }

    return taskMap;
  }

  /**
   * Get token usage events for a specific session recorded after a given timestamp.
   * Used to compute the token delta for a single Request when the orchestrator
   * handles the work directly (no WorkItem delegation).
   *
   * @param sessionName - The session to query (e.g. 'crewly-orc')
   * @param since - Only return events recorded at or after this time
   * @param until - Only return events before this time (defaults to now)
   * @returns Aggregated input tokens, output tokens, and cost in the window,
   *   plus the token-unit figures ({@link eventTokens}): `totalTokens` (raw,
   *   for reporting), `budgetTokens` (cost-weighted; what caps and budgets
   *   compare) and `cachedInputTokens`
   */
  getSessionUsageSince(
    sessionName: string,
    since: Date,
    until?: Date,
  ): { inputTokens: number; outputTokens: number; cost: number; totalTokens: number; budgetTokens: number; cachedInputTokens: number } {
    const record = this.sessions.get(sessionName);
    if (!record) return { inputTokens: 0, outputTokens: 0, cost: 0, totalTokens: 0, budgetTokens: 0, cachedInputTokens: 0 };

    const sinceMs = since.getTime();
    const untilMs = until ? until.getTime() : Infinity;
    let inputTokens = 0;
    let outputTokens = 0;
    let cost = 0;
    let totalTokens = 0;
    let budgetTokens = 0;
    let cachedInputTokens = 0;

    for (const event of record.events) {
      const eventMs = new Date(event.timestamp).getTime();
      if (eventMs >= sinceMs && eventMs <= untilMs) {
        inputTokens += event.input;
        outputTokens += event.output;
        // Cache-aware: a cache hit is billed at a fraction of the miss rate,
        // and the team budget gate keys on this figure — pricing every input
        // token at the miss rate would trip monthly USD caps ~40x early.
        cost += eventCostUsd(event);
        const t = eventTokens(event);
        totalTokens += t.total;
        budgetTokens += t.budget;
        cachedInputTokens += t.cachedInput;
      }
    }

    return { inputTokens, outputTokens, cost, totalTokens, budgetTokens: Math.round(budgetTokens), cachedInputTokens };
  }

  /**
   * Visit every recorded event at or after `since` (all events when omitted).
   * Read-only; used by the spend ledger for per-day / per-agent views.
   *
   * @param visit - Called with the session name and the event
   * @param since - Lower bound (inclusive)
   */
  forEachEvent(visit: (sessionName: string, event: TokenUsageEvent) => void, since?: Date): void {
    const sinceMs = since ? since.getTime() : -Infinity;
    for (const record of this.sessions.values()) {
      for (const event of record.events) {
        if (new Date(event.timestamp).getTime() >= sinceMs) visit(record.sessionName, event);
      }
    }
  }

  /**
   * Clear all tracked token usage data.
   */
  resetUsage(): void {
    this.sessions.clear();
  }

  /**
   * Start periodic flush of usage data to disk.
   *
   * Writes the current in-memory state to ~/.crewly/token-usage.json
   * at a fixed interval.
   */
  startPeriodicFlush(): void {
    if (this.flushTimer) return;
    this.flushTimer = setInterval(() => {
      this.flushToDisk().catch(() => {
        // Already logged by flushToDisk; the data is still in memory and
        // the next tick tries again.
      });
    }, FLUSH_INTERVAL_MS);
    // Allow Node to exit even if timer is running
    if (this.flushTimer.unref) {
      this.flushTimer.unref();
    }
  }

  /**
   * Stop the periodic flush timer.
   */
  stopPeriodicFlush(): void {
    if (this.flushTimer) {
      clearInterval(this.flushTimer);
      this.flushTimer = null;
    }
  }

  /**
   * Flush current usage data to disk.
   *
   * Writes sessions as a JSON array, atomically (temp file → fsync → rename),
   * so a full disk or a crash leaves the previous file intact instead of a
   * truncated one (the 2026-10-03 ledger loss). Refuses to write while a bad
   * ledger file is still waiting to be copied aside, and loads the file first
   * if this process never read it.
   *
   * @throws When the write fails (logged as an error) or the ledger is blocked
   */
  async flushToDisk(): Promise<void> {
    const filePath = path.join(this.storageDir, TOKEN_USAGE_FILE);
    if (this.loadState === 'not-loaded') await this.loadFromDisk();
    if (this.loadState === 'blocked') {
      // The file could not be read (EMFILE, EIO…) or is bad and could not be
      // copied aside. Read it again: a good file is merged, a bad one is set
      // aside now. Never write before one of those has happened.
      await this.loadFromDisk();
      if (this.loadState === 'blocked') {
        const err = new Error(`Token ledger not saved: ${this.blockedReason ?? 'the file on disk could not be read'}; the file was left as it is`);
        this.getLogger().error('Token ledger flush refused; the file on disk could not be read or set aside', { filePath, reason: this.blockedReason });
        throw err;
      }
    }
    const data = Array.from(this.sessions.values());
    try {
      await fs.mkdir(this.storageDir, { recursive: true });
      await atomicWriteFile(filePath, JSON.stringify(data, null, 2));
    } catch (err) {
      this.getLogger().error('Token ledger flush failed; the previous file was kept and the data is still in memory', {
        filePath,
        error: err instanceof Error ? err.message : String(err),
        code: (err as NodeJS.ErrnoException).code,
      });
      throw err;
    }
  }

  /**
   * Load previously persisted usage data from disk.
   *
   * Merges loaded data into the current in-memory state.
   *
   * - missing file: start fresh;
   * - unreadable or invalid file: copied aside to
   *   `token-usage.json.corrupt-<ts>`, logged as an error, start fresh;
   * - and if that copy fails, or the file cannot be read at all (EMFILE,
   *   EIO…): logged, and the ledger is marked blocked. Each flush reads it
   *   again first and writes only once it was loaded or set aside.
   */
  async loadFromDisk(): Promise<void> {
    const filePath = path.join(this.storageDir, TOKEN_USAGE_FILE);
    let read: JsonStoreRead<SessionUsageRecord[]>;
    try {
      read = await readJsonStore<SessionUsageRecord[]>(filePath, {
        validate: (d) => (Array.isArray(d) ? null : 'not a JSON array of session records'),
        logger: this.getLogger(),
      });
    } catch (err) {
      // Bad and could not be copied aside, or not readable at all (EMFILE,
      // EIO…). Either way nothing may be written over it yet.
      this.loadState = 'blocked';
      this.blockedReason = err instanceof CorruptJsonFileError
        ? `${err.reason}, and it could not be copied aside`
        : `read failed: ${err instanceof Error ? err.message : String(err)}`;
      this.getLogger().error('Token ledger could not be loaded; it will not be overwritten until it can be', { filePath, reason: this.blockedReason });
      return;
    }
    this.loadState = 'loaded';
    if (read.status !== 'ok') return;
    const records = read.data;
    dropCrossSessionDuplicates(records);
    for (const record of records) {
      const current = this.sessions.get(record.sessionName);
      if (!current) {
        this.sessions.set(record.sessionName, record);
        continue;
      }
      // Recorded in memory before the load ran: keep both, file first.
      const inMemory = new Set(current.events.map(ledgerEventKey));
      const fromFile = (record.events ?? []).filter((e) => !inMemory.has(ledgerEventKey(e)));
      current.events = [...fromFile, ...current.events].sort(byTimestamp);
      recomputeTotals(current);
    }
  }

  /**
   * Whether the ledger refuses to flush because its file is bad and could
   * not be copied aside yet.
   *
   * @returns True while blocked
   */
  isBlocked(): boolean {
    return this.loadState === 'blocked';
  }

  /**
   * Add historical events (a backfill) to a session.
   *
   * Unlike {@link recordUsage}, no trace or task context is attached — those
   * describe what the session is doing now, not on the day being rebuilt.
   * Events already in the ledger (in any session) are skipped: by
   * `messageId` when both sides have one, else by {@link ledgerEventKey}.
   *
   * @param sessionName - Session the events belong to
   * @param agentId - Agent id for a new session record
   * @param events - Events to add
   * @returns How many were added and how many were already present
   */
  importEvents(sessionName: string, agentId: string, events: TokenUsageEvent[]): { added: number; present: number } {
    const keys = new Set<string>();
    const ids = new Set<string>();
    this.forEachEvent((_s, e) => {
      keys.add(ledgerEventKey(e));
      if (e.messageId) ids.add(e.messageId);
    });
    let record = this.sessions.get(sessionName);
    let added = 0;
    let present = 0;
    for (const e of events) {
      const key = ledgerEventKey(e);
      if (keys.has(key) || (e.messageId && ids.has(e.messageId))) {
        present += 1;
        continue;
      }
      if (!record) {
        record = { sessionName, agentId, totalInput: 0, totalOutput: 0, eventCount: 0, events: [] };
        this.sessions.set(sessionName, record);
      }
      record.events.push({ ...e });
      keys.add(key);
      if (e.messageId) ids.add(e.messageId);
      added += 1;
    }
    if (record && added > 0) {
      record.events.sort(byTimestamp);
      recomputeTotals(record);
    }
    return { added, present };
  }

  /**
   * Whether an event is already in the ledger (any session).
   *
   * @param event - Candidate event
   * @returns True when present by message id or by {@link ledgerEventKey}
   */
  hasEvent(event: TokenUsageEvent): boolean {
    const key = ledgerEventKey(event);
    let found = false;
    this.forEachEvent((_s, e) => {
      if (!found && (ledgerEventKey(e) === key || (!!event.messageId && e.messageId === event.messageId))) found = true;
    });
    return found;
  }

  /** Component logger, created on first use. */
  private getLogger(): ComponentLogger {
    if (!this.logger) this.logger = LoggerService.getInstance().createComponentLogger('TokenUsage');
    return this.logger;
  }

  /**
   * Get the number of tracked sessions (for testing).
   *
   * @returns Number of sessions in the store
   */
  getSessionCount(): number {
    return this.sessions.size;
  }
}

/**
 * Identity of a ledger event for dedupe: the same turn recorded twice has
 * the same timestamp, token counts and model.
 *
 * @param e - Event
 * @returns Key
 */
export function ledgerEventKey(e: Pick<TokenUsageEvent, 'timestamp' | 'input' | 'cachedInput' | 'output' | 'model'>): string {
  return `${e.timestamp}|${e.input}|${e.cachedInput ?? ''}|${e.output}|${e.model}`;
}

/**
 * Order events oldest first (ISO timestamps sort as strings).
 *
 * @param a - Event
 * @param b - Event
 * @returns Sort order
 */
function byTimestamp(a: TokenUsageEvent, b: TokenUsageEvent): number {
  return a.timestamp < b.timestamp ? -1 : a.timestamp > b.timestamp ? 1 : 0;
}

/**
 * Recompute a record's totals from its events.
 *
 * @param r - Record; modified in place
 */
function recomputeTotals(r: SessionUsageRecord): void {
  r.eventCount = r.events.length;
  r.totalInput = r.events.reduce((n, e) => n + e.input, 0);
  r.totalOutput = r.events.reduce((n, e) => n + e.output, 0);
  const cached = r.events.reduce((n, e) => n + (e.cachedInput ?? 0), 0);
  if (r.totalCachedInput !== undefined || cached > 0) r.totalCachedInput = cached;
}

/**
 * Remove usage events that appear in more than one session's record.
 *
 * Two agents cannot produce the same usage at the same millisecond. Before the
 * shared-cwd guard (2026-09-22) the transcript sync pointed several agents at
 * one foreign transcript, so each of them was booked every one of its turns —
 * about 130 turns copied into five records. Every copy is dropped: the turns
 * belonged to none of them. Totals are recomputed for records that changed.
 *
 * @param records - Records as loaded from disk; modified in place
 * @returns How many events were removed
 */
export function dropCrossSessionDuplicates(records: SessionUsageRecord[]): number {
  const key = ledgerEventKey;
  const owners = new Map<string, Set<string>>();
  for (const r of records) {
    for (const e of r.events ?? []) {
      const k = key(e);
      const set = owners.get(k) ?? new Set<string>();
      set.add(r.sessionName);
      owners.set(k, set);
    }
  }
  let removed = 0;
  for (const r of records) {
    const before = (r.events ?? []).length;
    const seen = new Set<string>();
    r.events = (r.events ?? []).filter((e) => {
      const k = key(e);
      // Shared with another session: not this one's. Repeated within this
      // session (the same turn booked on several passes): keep one.
      if ((owners.get(k)?.size ?? 0) > 1 || seen.has(k)) return false;
      seen.add(k);
      return true;
    });
    if (r.events.length === before) continue;
    removed += before - r.events.length;
    recomputeTotals(r);
  }
  return removed;
}
